'use strict';

var constants = {
	APP_ADD_USER: 'APP_ADD_USER',
	APP_DELETE_USER: 'APP_DELETE_USER',
	GITHUB_GET_USER_SUCCESS: 'GITHUB_GET_USER_SUCCESS',
	GITHUB_GET_USER_FAIL: 'GITHUB_GET_USER_FAIL'
};

export default constants;
