'use strict';

var constants = {
	APP_ADD_USER: 'APP_ADD_USER',
	APP_DELETE_USER: 'APP_DELETE_USER',
	GITHUB_GET_USER_SUCCESS: 'GITHUB_GET_USER_SUCCESS',
	GITHUB_GET_USER_FAIL: 'GITHUB_GET_USER_FAIL',
	GITHUB_CLEAR_USER_INFO: 'GITHUB_CLEAR_USER_INFO',
	LOADING_UPDATE_STATE: 'LOADING_UPDATE_STATE'
};

export default constants;
